#:schema node_modules/wrangler/config-schema.json
name = "vultrctl-bot"
main = "src/index.ts"
compatibility_date = "2024-12-16"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
